import {
  campTranslation,
  officeTranslation,
  schoolTranslation,
} from "./scene-translations";

export const sceneMoveMap: Record<
  number,
  Record<string, Record<string, number> | number | string | Element | null>
> = {
  1: {
    campX: campTranslation[1].desktop,
    campXMobile: campTranslation[1].mobile,
    backgroundClass: "background-scene-one",
    backgroundElement: document.querySelector(".background-scene-one"),
    contentClass: "content__one",
    contentElement: document.querySelector(".content__one"),
    emailLinkElement: document.querySelector(".email-link__one"),
    emailLinkClass: "email-link__one",
    lightX: 7,
    lightY: 10,
    lightZ: -1,
    officeX: officeTranslation[1].desktop,
    officeXMobile: officeTranslation[1].mobile,
    particlesClass: "particle-wrapper",
    particlesElement: document.querySelector(".particle-wrapper__one"),
    resumeButtonClass: "resume-button__one",
    resumeButtonElement: document.querySelector(".resume-button__one"),
    schoolX: schoolTranslation[1].desktop,
    schoolXMobile: schoolTranslation[1].mobile,
  },
  2: {
    campX: campTranslation[2].desktop,
    campXMobile: campTranslation[2].mobile,
    backgroundClass: "background-scene-two",
    backgroundElement: document.querySelector(".background-scene-two"),
    contentClass: "content__two",
    contentElement: document.querySelector(".content__two"),
    emailLinkClass: "email-link__two",
    emailLinkElement: document.querySelector(".email-link__two"),
    lightX: -5,
    lightY: 10,
    lightZ: 2,
    officeX: officeTranslation[2].desktop,
    officeXMobile: officeTranslation[2].mobile,
    particlesClass: "particle-wrapper",
    particlesElement: document.querySelector(".particle-wrapper__two"),
    resumeButtonClass: "resume-button__two",
    resumeButtonElement: document.querySelector(".resume-button__two"),
    schoolX: schoolTranslation[2].desktop,
    schoolXMobile: schoolTranslation[2].mobile,
  },
  3: {
    campX: campTranslation[3].desktop,
    campXMobile: campTranslation[3].mobile,
    backgroundClass: "background-scene-three",
    backgroundElement: document.querySelector(".background-scene-three"),
    contentClass: "content__three",
    contentElement: document.querySelector(".content__three"),
    emailLinkElement: document.querySelector(".email-link__three"),
    emailLinkClass: "email-link__three",
    lightX: -5.5,
    lightY: 9.5,
    lightZ: 3,
    officeX: officeTranslation[3].desktop,
    officeXMobile: officeTranslation[3].mobile,
    particlesClass: "particle-wrapper",
    particlesElement: document.querySelector(".particle-wrapper__three"),
    resumeButtonClass: "resume-button__three",
    resumeButtonElement: document.querySelector(".resume-button__three"),
    schoolX: schoolTranslation[3].desktop,
    schoolXMobile: schoolTranslation[3].mobile,
  },
};
